export const ROLES = {
  EMISOR: 'EMISOR',
  SUPERVISOR: 'SUPERVISOR',
  EJECUTANTE: 'EJECUTANTE',
  ADMIN: 'ADMIN',
  RTO_MANT: 'RTO_MANT',
  EHS: 'EHS',
  LIDER: 'LIDER',
};

export const ALL_ROLES = [ROLES.EMISOR, ROLES.SUPERVISOR, ROLES.EJECUTANTE, ROLES.ADMIN, ROLES.EHS, ROLES.LIDER];
