export const ROLES = {
  EMISOR: 'EMISOR',
  SUPERVISOR: 'SUPERVISOR',
  EJECUTANTE: 'EJECUTANTE',
  ADMIN: 'ADMIN',
  RTO_MANT: 'RTO_MANT',
};

export const ALL_ROLES = [ROLES.EMISOR, ROLES.SUPERVISOR, ROLES.EJECUTANTE, ROLES.ADMIN];
